name: Windows - RustDesk

on:
  workflow_dispatch:

jobs:
  build:
    name: Start RustDesk Session
    runs-on: windows-latest
    timeout-minutes: 9999
    
    steps:
      - name: Download and Install RustDesk
        run: |
          Invoke-WebRequest -Uri "https://github.com/rustdesk/rustdesk/releases/download/1.3.8/rustdesk-1.3.8-x86_64.exe" -OutFile "rustdesk.exe"
                    
          # Download RustDesk using a custom User-Agent to avoid GitHub blocks
          

          # Install RustDesk silently
          Start-Process -FilePath .\rustdesk.exe -ArgumentList "/S" -NoNewWindow -Wait

          # Set RustDesk to run as a service
          $RustDeskPath = "C:\Program Files\RustDesk\rustdesk.exe"
          Start-Process -FilePath $RustDeskPath -ArgumentList "--service install" -NoNewWindow -Wait
          Start-Process -FilePath $RustDeskPath -ArgumentList "--service start" -NoNewWindow -Wait
          Write-Output "RustDesk is running in service mode..."
          
          
      
      - name: Set Custom RustDesk ID and Password
        run: |
          $CustomID = "987-654-321"
          $CustomPassword = "MySecurePass123"
          $ConfigPath = "$env:APPDATA\RustDesk\config\RustDesk.toml"
          
          # Create RustDesk config folder if it doesn’t exist
          if (!(Test-Path "$env:APPDATA\RustDesk\config")) {
              New-Item -ItemType Directory -Path "$env:APPDATA\RustDesk\config"
          }

          # Write custom ID and password to config file
          Set-Content -Path $ConfigPath -Value @"
          [network]
          id = "$CustomID"
          password = "$CustomPassword"
          "@

      - name: Start RustDesk Service with Custom ID
        run: |
          Start-Process -FilePath "C:\Program Files\RustDesk\rustdesk.exe"
          Start-Sleep -Seconds 10

      - name: Display Custom ID and Password
        run: |
          echo "Custom RustDesk ID: 987-654-321"
          echo "Custom RustDesk Password: MySecurePass123"
          echo "Use this ID and Password to connect via RustDesk"

      - name: Keep Session Alive
        run: |
          while ($true) { Start-Sleep -Seconds 3600 }
