name: Windows - RustDesk

on:
  workflow_dispatch:

jobs:
  build:
    name: Start RustDesk Session
    runs-on: windows-latest
    timeout-minutes: 9999
    
    steps:
      - name: Download and Install RustDesk
        run: |
          Invoke-WebRequest -Uri "https://github.com/rustdesk/rustdesk/releases/download/1.2.2/rustdesk-1.2.2-windows_x64.exe" -OutFile "rustdesk.exe"
          Start-Process -FilePath .\rustdesk.exe -ArgumentList "/S" -NoNewWindow -Wait
      
      - name: Set Custom RustDesk ID and Password
        run: |
          $CustomID = "244-544-006"
          $CustomPassword = "Wmine@24$"
          $ConfigPath = "$env:APPDATA\RustDesk\config\RustDesk.toml"
          
          # Create RustDesk config folder if it doesn’t exist
          if (!(Test-Path "$env:APPDATA\RustDesk\config")) {
              New-Item -ItemType Directory -Path "$env:APPDATA\RustDesk\config"
          }

          # Write custom ID and password to config file
          Set-Content -Path $ConfigPath -Value @"
          [network]
          id = "$CustomID"
          password = "$CustomPassword"
          "@

      - name: Start RustDesk Service with Custom ID
        run: |
          Start-Process -FilePath "C:\Program Files\RustDesk\rustdesk.exe"
          Start-Sleep -Seconds 10

      - name: Display Custom ID and Password
        run: |
          echo "Custom RustDesk ID: 987-654-321"
          echo "Custom RustDesk Password: MySecurePass123"
          echo "Use this ID and Password to connect via RustDesk"

      - name: Keep Session Alive
        run: |
          while ($true) { Start-Sleep -Seconds 3600 }
